openapi: 3.0.1
info:
  title: Stuff to do
  version: 1.0.0
servers:
- url: /v1
paths:
  /players:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Players'
          description: Array of players
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpected error
      summary: Get all players
    post:
      responses:
        "201":
          content: {}
          description: Null response
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: unexpexted error
      summary: Create a player
components:
  schemas:
    Players:
      items:
        $ref: '#/components/schemas/Player'
      type: array
    Player:
      example:
        name: name
        id: 0
        tag: tag
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
        tag:
          type: string
      required:
      - id
      - name
      type: object
    Error:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
      required:
      - code
      - message
      type: object
